### ISSUE TITLE
Invalid username or password error when executed in different job than actions/checkout

### ISSUE THREAD

**Issue by elendil-software** [rickstaa/action-create-tag#18]
**Describe the bug**

when rickstaa/action-create-tag@v1 is executed in an other job than the one where actions/checkout is executed I get this error

> remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/elendil-software/name-of-the-repo.git/'

**To Reproduce**

Here is a workflow I used to reproduce the problem.
It create a tag in the same job than the checkout action, and another one in other job. The first tag is correctly created, but the second one produce the error. 
The repository content is shared between jobs with an artifact.

```yml
name: 'Test Tag Workflow'

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  init:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    # This tag is correctly created
    - name: Create Tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: 3.0.0
        message: "3.0.0"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload source directory
      uses: actions/upload-artifact@v3
      with:
        name: 1-after-clone
        path: ./ 
        
  tag:
    runs-on: ubuntu-latest
    needs: init
    steps:
    - name: Download source directory
      uses: actions/download-artifact@v3
      with:
        name: 1-after-clone
        
    # This call produce the error
    - name: Create Tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: 3.0.1
        message: "3.0.1"
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
Should work in both cases
