### ISSUE TITLE
Failed to resolve '' as a valid ref.

### ISSUE THREAD

**Issue by pacroy** [rickstaa/action-create-tag#3]
When using this action in a push event:

```yaml
name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: "Tag minor version"
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "v0.7"
        message: "Test message"
        force_push_tag: true
```

Got error:

```console
[action-create-tag] Create tag 'v0.7'.
fatal: Failed to resolve '' as a valid ref.
```

Resolved by adding optional input `commit_sha`:

```yaml
    - name: "Tag minor version"
      uses: rickstaa/action-create-tag@v1
      with:
        tag: "v0.7"
        message: "Test message"
        force_push_tag: true
        commit_sha: ${{ github.sha }}
```

Expect that the optional `commit_sha` variable is not specified and use the current commit automatically.
