### ISSUE TITLE
GITHUB_OUTPUT: parameter not set error

### ISSUE THREAD

**Issue by tamasbege** [rickstaa/action-create-tag#32]
Hello, I am trying to use your action in my workflow and I am getting the following error when running it:

`/entrypoint.sh: line 29: GITHUB_OUTPUT: parameter not set`

Am I the only one, hence am I doing something wrong? I am using the latest version 1.6.1 from the action btw.

This is how my call looks like:
``` 
- name: Create git tag
  uses: rickstaa/action-create-tag@v1.6.1
  with:
     tag: "${{ inputs.new_release_version }}"
     message: "Release ${{ inputs.new_release_version}}"
```
